### PR TITLE
Rewrote the way some of the things were installing

### PR DESCRIPTION
**Pull request by ghost**
Hi Steve,

I've made some changes, I hope they are not too extreme, I am at the beginning with this contribution thing.

Please give me your thought when you get the chance

### CODE REVIEW

**Comment by SteveParson** [comment]
Hi Adrian,

First, thank you for your contribution. I am happy to see that IntelliJ and Pycharm are now available as snaps. That makes things much better.

It looks like you need another package in order to change the way that kops is installed. I received this error while testing: 

`default: fatal: [127.0.0.1]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}`.

A quick google search says that installing `python-jmespath` will resolve the error. Can you add this to the set of common dependencies or remove that particular change? Once you've done that, please resubmit your PR and I will be happy to test and approve once it is ready.

Please note that I've received multiple PRs today. I'm reviewing them and integrating them in order. so make sure you pull down the latest master so I can merge your changes. I appreciate your help!

**Comment by ghost** [comment]
Hi Steve,

Thank you for you review, I've added the missing package. Let me know how it goes in testing.

Cheers

**Comment by SteveParson** [comment]
It still has the same problem, maybe that is the wrong package. I am sure that there are different ones for python2 and python3. I'd be happy to test your PR once you have confirmed that everything works!

**Comment by ghost** [comment]
Hi Steve,

I did make some changes, tested it and now the code does not break. Please test it when you get the chance and let me know if it needs more work.
Thanks

**Comment by SteveParson** [comment]
Thanks for your contribution!

**Pull request merged**
